version: '2'
services:
    db:
      image: postgres
      container_name: db
      restart: always
      ports:
        - 5002:5432
      env_file:
        - .env
      volumes:
        - pg:/var/lib/postgresql/data

    node:
      container_name: students_image
      build: .
      ports:
        - 5000:5000
      depends_on:
        - db
      env_file:
        - .env
volumes:
  pg:
